#!/bin/sh

# rsyslog munin plugin
# graphs processed messages per action
# 0.20141202-01 aneuhold@libertyglobal.com
# /etc/munin/plugins/syslog_received


##############################################################################
# prerequisites
##############################################################################
#
# 1.) enable rsyslog stats via impstat
# vim /etc/rsyslog.conf
#
# #### statistic http://www.rsyslog.com/doc/impstats.html #####
# module(load="impstats"
#     interval="300"
#     severity="7"
#     resetCounters="on"
#     log.syslog="off" /* need to turn log stream logging off! */
#     log.file="/var/log/rsyslog.stats"
#     )
#
# 2.) change permissions, so munin ca read it
# chmod 0664 /etc/logrotate.d/rsyslogstats
#
# 3.) rotate stats file
# cat <<'EOF' > /etc/logrotate.d/rsyslogstats
# /var/log/rsyslog.stats {
#    daily
#    rotate 7
#    compress
#    copytruncate
#    # create 0644 root root # obsolete if copytruncate
#    notifempty
#    missingok
# }
#EOF
#
##############################################################################
##############################################################################

FILE=/var/log/rsyslog.stats
IFS=:

if [ "$1" == "config" ]; then
cat <<EOF
graph_title number of processed syslog messages
graph_category network
graph_vlabel messages per 5-minutes
graph_order received
received.label syslog messages processed
received.draw AREA
EOF
else
    if [ -f $FILE ] && [ -r $FILE ]; then
    # Sat Nov 29 16:07:27 2014: action 1: processed=51802 failed=0 suspended=0 suspended.duration=0 resumed=0

    # action 1
    /usr/bin/tac $FILE| P="action 1:" awk '$0 ~ ENVIRON["P"] {split($8,a,"=") ; print "received.value " a[2]; exit}'
    #tac /var/log/rsyslog.stats| P="action 1:" awk '$0 ~ ENVIRON["P"] {split($8,a,"=") ; print "received.value " a[2]; exit}'

    # action 6
    # tac /var/log/rsyslog.stats| P="action 6:" awk '$0 ~ ENVIRON["P"] {split($8,a,"=") ; print "received.value " a[2]; exit}'

    # action 8
    # tac /var/log/rsyslog.stats| P="action 8:" awk '$0 ~ ENVIRON["P"] {split($8,a,"=") ; print "received.value " a[2]; exit}'

    unset IFS

    else
            echo "File not found!"
            exit 1
    fi
fi
